### ISSUE TITLE
Try to fix these errors in branch 2body.

### ISSUE THREAD

**Issue by DeathStocker** [DeathStocker/solar_system#5]
Try to fix at least some if not all.
Ignore the `unused variable` ones. They are not so important as of now.

![screenshot from 2016-08-28 17 43 00](https://cloud.githubusercontent.com/assets/14164924/18033611/640eb77a-6d47-11e6-8a7f-67ac1bcc1301.png)

**Comment by munishkr** [comment]
The errors have been fixed except for there is some inheritance problem of the header file

**Comment by DeathStocker** [comment]
@munishkr, changes are not in main() and the changes have not yet been pushed.
Issue reopened.

**Comment by DeathStocker** [comment]
Modified the `2body` branch. Fixes #5
