### ISSUE TITLE
Weird behaviour of the moon. [Branch - 3-body]

### ISSUE THREAD

**Issue by DeathStocker** [DeathStocker/solar_system#6]
For some reason, the moon won't revolve around the earth.
Maybe due to the relative velocities and positions.
Other planets are doing fine around the sun, but if there is another body, which is supposed to orbit a planet, its path goes weirdly around the Sun.

@munishkr , look into this ASAP.

**Comment by munishkr** [comment]
@DeathStocker  the gravitational force has not been updated the formula is for 2 bodies and we should modify the same function instead of a new one.

**Comment by munishkr** [comment]
@DeathStocker the previous comment was incorrect after verifying the code. Changing the graph color helped in identifying actual trajectories of earth and moon which came out to be correct according to the code.
